"""removed created_by field from task table and relationship between user and task

Revision ID: 0ff571ea9a0f
Revises: 7495ecf8aede
Create Date: 2025-11-04 19:43:37.596794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff571ea9a0f'
down_revision: Union[str, Sequence[str], None] = '7495ecf8aede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
